abbr -a -- e 'echo'
abbr -a -- t 'type'

abbr -a -- cp 'cp -iv'
abbr -a -- cpr 'cp -ivR'
abbr -a -- mv 'mv -iv'
abbr -a -- rm 'rm -iv'
abbr -a -- rmr 'rm -rf'

abbr -a -- l '$LS -lhag'

abbr -a -- v '$EDITOR'
abbr -a -- n '$EDITOR'

abbr -a -- r '$GREP'

abbr -a -- ppath 'echo $PATH | tr " " \\n | nl'

abbr -a -- g 'git'
abbr -a -- gs 'git switch'
abbr -a -- g- 'git switch -'
abbr -a -- gsw 'git switch'
abbr -a -- gsc 'git switch -c'
abbr -a -- gso 'git switch --track origin/'
abbr -a -- gco 'git checkout'
abbr -a -- gcb 'git checkout -b'
abbr -a -- glg 'git log'
abbr -a -- glp 'git log -p'
abbr -a -- gln 'git log --name-status'
abbr -a -- gst 'git status'
abbr -a -- gpl 'git pull'
abbr -a -- gcl 'git clone'
abbr -a -- scl 'scalar clone'
abbr -a -- gbr 'git better-branch'
abbr -a -- gbd 'git branch -d'
abbr -a -- gbl 'git blame -w -CCC'
abbr -a -- gdi 'git diff'
abbr -a -- gds 'git diff --staged'
abbr -a -- gad 'git add'
abbr -a -- gaa 'git add --all'
abbr -a -- gci 'git commit'
abbr -a -- gca 'git commit --amend'
abbr -a -- gcn 'git commit --amend --no-edit'
abbr -a -- gcf 'git commit --fixup='
abbr -a -- gcm 'git commit -m'
abbr -a -- gce 'git commit --allow-empty'
abbr -a -- gps 'git push'
abbr -a -- gpf 'git push --force-with-lease'
abbr -a -- grs 'git restore'
abbr -a -- gwa 'git worktree add -b'
abbr -a -- gms 'git maintenance start'
abbr -a -- grs 'git restore --staged'
abbr -a -- grss 'git restore --staged . && git restore .'
abbr -a -- gprv 'git checkout HEAD^'
abbr -a -- gnxt 'git checkout (git rev-list HEAD..demo-end | tail -1)'

abbr -a -- ch 'chezmoi'
abbr -a -- cha 'chezmoi add'
abbr -a -- che 'chezmoi edit --apply'
abbr -a -- chs 'chezmoi status'
abbr -a -- chc 'chezmoi cd'
abbr -a -- chd 'chezmoi diff'

# echo "Added" (abbr -l | wc -l | tr -d ' ') "abbreviations"
